server:
  port: 8090

file:
  prefix: file.log

logging:
  config:
    classpath: log4j2.xml
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://hybrid01.debugboxcreate4762.sensorsdata.cloud:3305/metadata
#    username: work
#    password: PFz2HdG/KZ
#    type: com.zaxxer.hikari.HikariDataSource

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: mysql